# Generated by Django 6.0.3 on 2026-03-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_apicache_remove_skilldata_demand_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilldata',
            name='demand_score',
            field=models.IntegerField(default=0),
        ),
    ]
